services:
  app:
    build: .
    image: jellyfin-subscriptions:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - sqlite-data:/app/prisma
    restart: unless-stopped

volumes:
  sqlite-data:
